# please also refer to:
# ``rosed arm_components_name_manager JointsTemplate.yaml``
jaco:
    # Name of the palm link.
    palm_link: jaco_6_hand_limb
    
    # Name of the end effector link.
    effector_link: jaco_6_hand_limb

    # Names of the arm joints *without* the gripper joints.
    arm_joints:
        - jaco_arm_0_joint
        - jaco_arm_1_joint
        - jaco_arm_2_joint
        - jaco_arm_3_joint
        - jaco_arm_4_joint
        - jaco_arm_5_joint

    # initial ("Home") pose of the arm joints. Has to be the same
    # order as arm_joints.
    arm_joint_init:
        - -3.102659
        - 0.589908
        - -3.572422
        - 0.317386
        - 0.892403
        - -0.746554

    # Maximum velocities for arm
    arm_joint_max_vel:
        - 0.8
        - 0.8
        - 0.8
        - 0.8
        - 0.8
        - 0.8

    # Maximum forces for arm
    arm_joint_max_force:
        - 8 
        - 8
        - 4
        - 2
        - 2
        - 2


    # All links which are in-between (and directly before and after)
    # the arm_joints. It does however *not* include the palm_link
    # because this is specified separately.
    arm_links:
        - jaco_0_baseA
        - jaco_0_base_limb
        - jaco_1_shoulder_limb
        - jaco_2_upperarm_limb
        - jaco_3_forearm_limb
        - jaco_4_upperwrist_limb
        - jaco_5_lowerwrist_limb
        - jaco_ring_1
        - jaco_ring_2
        - jaco_ring_3
        - jaco_ring_4
        - jaco_ring_5
        - jaco_ring_6
            
    # All joints of the "gripper". The gripper is the part of the
    # arm used to grasp/grip objects. 
    # Essentially, they are the "finger joints".
    gripper_joints:
        - jaco_finger_joint_0
        - jaco_finger_joint_2
        - jaco_finger_joint_4

    # initial ("Home") pose of the gripper joints. Has to be the same
    # order as gripper_joints.
    gripper_joint_init:
        - 0.1
        - 0.1
        - 0.1
    # -0.0043633

    # Maximum velocities for gripper
    gripper_joint_max_vel:
        - 0.3 
        - 0.3 
        - 0.3 

    # Maximum forces for gripper
    gripper_joint_max_force:
        - 2
        - 2 
        - 2



    # All links which are in-between (and directly before and after)
    # the gripper_joints. It does however *not* include the palm_link
    # because this is specified separately.
    gripper_links:
        - jaco_fingers_base_link
        - jaco_7_finger_mount_index
        - jaco_8_finger_index
        - jaco_9_finger_index_tip
        - jaco_7_finger_mount_thumb
        - jaco_8_finger_thumb
        - jaco_9_finger_thumb_tip
        - jaco_7_finger_mount_pinkie
        - jaco_8_finger_pinkie
        - jaco_9_finger_pinkie_tip

    # Position controller names. Does not need to be specified
    # if ArmComponentsNameManager instance is not used to read PID values
    # Has to be in same order as arm_joints.
    arm_position_controller_names:
        - jaco_arm_0_joint_position_controller
        - jaco_arm_1_joint_position_controller
        - jaco_arm_2_joint_position_controller
        - jaco_arm_3_joint_position_controller
        - jaco_arm_4_joint_position_controller
        - jaco_arm_5_joint_position_controller
    
    # Has to be in same order as arm_joints.
    # arm_effort_controller_names:
    
    # Has to be in same order as gripper_joints.
    gripper_position_controller_names:
        - jaco_finger_joint_0_position_controller
        - jaco_finger_joint_2_position_controller
        - jaco_finger_joint_4_position_controller

    # Velocity controller names. Does not need to be specified
    # if ArmComponentsNameManager instance is not used to read PID values
    # Has to be in same order as arm_joints.
    arm_velocity_controller_names:
        - jaco_arm_0_joint_velocity_controller
        - jaco_arm_1_joint_velocity_controller
        - jaco_arm_2_joint_velocity_controller
        - jaco_arm_3_joint_velocity_controller
        - jaco_arm_4_joint_velocity_controller
        - jaco_arm_5_joint_velocity_controller
    
    # Has to be in same order as gripper_joints.
    gripper_velocity_controller_names:
        - jaco_finger_joint_0_velocity_controller
        - jaco_finger_joint_2_velocity_controller
        - jaco_finger_joint_4_velocity_controller

    # Has to be in same order as gripper_joints.
    # gripper_effort_controller_names:
