# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: Arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - jaco_arm_0_joint
    - jaco_arm_1_joint
    - jaco_arm_2_joint
    - jaco_arm_3_joint
    - jaco_arm_4_joint
    - jaco_arm_5_joint
    - jaco_finger_joint_0
    - jaco_finger_joint_2
    - jaco_finger_joint_4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
controller_list:
  - name: Arm_controller
    action_ns: joint_trajectory_execution
    default: True
    type: FollowJointTrajectory
    joints:
      - jaco_arm_0_joint
      - jaco_arm_1_joint
      - jaco_arm_2_joint
      - jaco_arm_3_joint
      - jaco_arm_4_joint
      - jaco_arm_5_joint
  - name: All_controller
    action_ns: joint_trajectory_execution
    default: True
    type: FollowJointTrajectory
    joints:
      - jaco_arm_0_joint
      - jaco_arm_1_joint
      - jaco_arm_2_joint
      - jaco_arm_3_joint
      - jaco_arm_4_joint
      - jaco_arm_5_joint
      - jaco_finger_joint_0
      - jaco_finger_joint_2
      - jaco_finger_joint_4
